server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-management-service
          uri: http://localhost:8383
          predicates:
            - Path=/api/users/**
        - id: club-management-service
          uri: http://localhost:8181
          predicates:
            - Path=/api/clubs/**
        - id: event-management-service
          uri: http://localhost:8282
          predicates:
            - Path=/api/events/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/